const fs = require("fs");
const path = require("path");

const asset_manifest = JSON.parse(
  fs.readFileSync("./build/asset-manifest.json", { encoding: "utf8" })
);
const startupScript = fs.readFileSync(
  path.join("./build", asset_manifest["runtime~main.js"])
);

const scripts = Object.keys(asset_manifest)
  .filter(key => key === "main.js" || key.endsWith(".chunk.js"))
  .map(key => asset_manifest[key]);

const styles = Object.keys(asset_manifest)
  .filter(key => key === "main.css" || key.endsWith(".chunk.css"))
  .map(key => asset_manifest[key]);

fs.writeFileSync(
  "./build/udir_sammenlign_widget.js",
  `// Generated by src/scripts/widgetgenerator.js

${startupScript}
  
(function(){
    // Figure out which domain this udir_sammenlign_widget.js is hosted at,
    // and assume all related files are from the same domain.
    var jsscript = document.getElementsByTagName("script");
    var domain = "";
    for (var i = 0; i < jsscript.length; i++) {
      var pattern = /\\/udir_sammenlign_widget.js/i; // the name of your js, whose source you are looking for
      if ( pattern.test( jsscript[i].getAttribute("src") ) )
        domain = jsscript[i].getAttribute("src").replace("udir_sammenlign_widget.js","");
    }
    // Include config.js for server side config on the window object
    var configScript = document.createElement('script');
    configScript.src = domain + "/config.js";
    document.body.append(configScript);


    // Include required scripts for the widget
    ${scripts
      .map(
        (script, i) => `var script${i} = document.createElement('script');
    script${i}.src = domain + "${script}";
    document.body.append(script${i});
`
      )
      .join("\n    ")}
    // Include styles
    ${styles
      .map(
        (style, i) => `var style${i} = document.createElement('link');
    style${i}.rel = "stylesheet";
    style${i}.href = domain + "${style}";
    document.head.appendChild(style${i});
`
      )
      .join("\n    ")}
})()
`
);

// Ensure build/config.js exists
if (!fs.existsSync("./build/config.js")) {
  fs.writeFileSync(
    "./build/config.js",
    `//window.sammenlignBackendURL = "https://sammenlign.utdanning.no"`
  );
}
